on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: "Checkout sasview.github.io Repository"
        uses: actions/checkout@v5
        with:
          repository: sasview/sasview.github.io
          ref: master
          ssh-key: ${{ secrets.API_TOKEN_GITHUB }}
      - name: "Download archived markdown file"
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event.workflow_run.id }}
      - name: "Copy Markdown File Back Into Workspace"
        run: cp -rf ./SASVIEW_publications.md ./publications.md
      - name: "Commit And Push Any Changes to Github"
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git add ./publications.md
            git config --global user.name ${{ secrets.GIT_USER_NAME }}
            git config --global user.email ${{ secrets.GIT_EMAIL }}
            git commit -m "publications auto-update"
            git push
          fi
