on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout sasview.github.io Repository"
        uses: actions/checkout@v5
        with:
          repository: sasview/sasview.github.io
          ref: master
          ssh-key: ${{ secrets.API_TOKEN_GITHUB }}
      - name: "Download archived markdown file"
        uses: actions/download-artifact@v5
        with:
          name: SASVIEW_publications.md
      - name: "Copy Markdown File Back Into Workspace"
        run: cp -f ./SASVIEW_publications.md ./publications.md
      - name: "Commit And Push Any Changes to Github"
        run: |
          git diff
          if ! git diff-index --quiet HEAD --; then
            git config --global user.name ${{ secrets.GIT_USER_NAME }}
            git config --global user.email ${{ secrets.GIT_EMAIL }}
            git commit ./publications.md -m "publications auto-update `date -d now`"
            git push
          fi
