on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout sasview.github.io Repository"
        uses: actions/checkout@v5
        with:
          repository: sasview/sasview.github.io
          ref: master
          persist-credentials: false
          fetch-depth: 0
      - name: "Download archived markdown file"
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event.workflow_run.id }}
      - name: "Copy Markdown File Back Into Workspace"
        run: cp -rf ./SASVIEW_publications.md ./publications.md
      - name: "Commit And Push Any Changes to Github"
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add ./publications.md
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "publications auto-update"
          else
            echo "No changes found. Skipping push."
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Publications auto-update'
          body: 'Automatic update of the publications lists from the sasview/saspubs repo CI.'
          branch: 'auto-update-pubs'
          base: 'master'
          draft: false
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
