on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: "Checkout sasview.github.io Repository"
        uses: actions/checkout@v5
        with:
          repository: sasview/sasview.github.io
          ref: master
          ssh-key: ${{ secrets.API_TOKEN_GITHUB }}
          persist-credentials: false
          fetch-depth: 0
      - name: "Download archived markdown file"
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event.workflow_run.id }}
      - name: "Copy Markdown File Back Into Workspace"
        run: cp -rf ./SASVIEW_publications.md ./publications.md
      - name: "Commit And Push Any Changes to Github"
        run: |
          echo "Checking for git changes..."
          # TODO: This command is throwing an error. Fix it!
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes found in git status"
            git add ./publications.md
            echo "Changes added to git"
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            echo "Git Config updated"
            git commit -m "publications auto-update"
            echo "Local changes committed"
          else
            echo "No changes found. Skipping push."
          fi
      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          ssh: true
          branch: ${{ github.ref }}
